- hosts: NewFabric
  connection: httpapi
  gather_facts: false
  collections:
    - dellemc.enterprise_sonic
  tasks:

    - name: Perform factory reset on Dell SONiC switch
      sonic_command:
        commands:
          - "sudo config reload -y"  # Cargar la configuración de fábrica
          - "sudo reboot"             # Reiniciar el switch para aplicar los cambios
      become: yes                    # Usar permisos elevados
      ignore_errors: yes             # Ignorar errores si el switch se reinicia antes de completar

    - name: Wait for switch to come back online after reload
      wait_for:
        timeout: 300                 # Esperar hasta 5 minutos
        host: "{{ inventory_hostname }}"
        port: 22                     # Esperar hasta que el puerto SSH esté activo
        state: started

    - name: Ensure switch is reachable after reset
      ping:
