is_border_leaf: true
lacp_pcs: []
loopback3_ip: 1.1.1.1/32
mclag_member_pcs: []
sonic_bgp:
  - bestpath:
      as_path:
        multipath_relax: true
    bgp_as: '{{ bgp_asn }}'
    router_id: '{{ bgp_router_id }}'
  - bgp_as: '{{bgp_asn}}'
    vrf_name: VrfTenant1
  - bgp_as: '{{bgp_asn}}'
    vrf_name: VrfTenant2
  - bgp_as: '{{ bgp_asn }}'
sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 16
          redistribute:
            - protocol: connected
          safi: unicast
        - advertise_all_vni: true
          afi: l2vpn
          safi: evpn
          vnis:
            - rt_in:
                - auto
                - 20100:100
              rt_out:
                - auto
                - 10100:100
              vni_number: 10100
            - rt_in:
                - auto
                - 20200:200
              rt_out:
                - auto
                - 10200:200
              vni_number: 10200
            - rt_in:
                - auto
                - 20201:201
              rt_out:
                - auto
                - 10201:201
              vni_number: 10201
            - rt_in:
                - auto
                - 20202:202
              rt_out:
                - auto
                - 10202:202
              vni_number: 10202
            - rt_in:
                - auto
                - 20301:301
              rt_out:
                - auto
                - 10301:301
              vni_number: 10301
            - rt_in:
                - auto
                - 20302:302
              rt_out:
                - auto
                - 10302:302
              vni_number: 10302
            - rt_in:
                - auto
                - 20303:303
              rt_out:
                - auto
                - 10303:303
              vni_number: 10303
            - rt_in:
                - auto
                - 20304:304
              rt_out:
                - auto
                - 10304:304
              vni_number: 10304
            - rt_in:
                - auto
                - 20305:305
              rt_out:
                - auto
                - 10305:305
              vni_number: 10305
            - rt_in:
                - auto
                - 20306:306
              rt_out:
                - auto
                - 10306:306
              vni_number: 10306
            - rt_in:
                - auto
                - 20307:307
              rt_out:
                - auto
                - 10307:307
              vni_number: 10307
            - rt_in:
                - auto
                - 20308:308
              rt_out:
                - auto
                - 10308:308
              vni_number: 10308
            - rt_in:
                - auto
                - 20309:309
              rt_out:
                - auto
                - 10309:309
              vni_number: 10309
            - rt_in:
                - auto
                - 20310:310
              rt_out:
                - auto
                - 10310:310
              vni_number: 10310
    bgp_as: '{{bgp_asn}}'
  - address_family:
      afis:
        - afi: l2vpn
          rd: '{{bgp_asn}}:1'
          route_advertise_list:
            - advertise_afi: ipv4
          rt_in:
            - auto
            - '2061:1'
          rt_out:
            - auto
            - '1061:1'
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: VrfTenant1
  - address_family:
      afis:
        - afi: l2vpn
          rd: '{{bgp_asn}}:2'
          route_advertise_list:
            - advertise_afi: ipv4
          rt_in:
            - auto
            - '2062:1'
          rt_out:
            - auto
            - '1062:1'
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: VrfTenant2
sonic_bgp_neighbors:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: Eth1/7
        peer_group: spine-leaf
      - neighbor: Eth1/6
        peer_group: spine-leaf
    peer_group:
      - '{{sonic_bgp_spineleaf_peergroup}}'
      - '{{sonic_bgp_external_pg_entry}}'
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: 192.168.10.2
        remote_as:
          peer_as: 65203
    vrf_name: VrfTenant1
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: 192.168.10.6
        remote_as:
          peer_as: 65203
    vrf_name: VrfTenant1
sonic_bgp_neighbors_af:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/7
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/6
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family:
          - activate: true
            afi: ipv4
            safi: unicast
        neighbor: 192.168.10.2
    vrf_name: VrfTenant1
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family:
          - activate: true
            afi: ipv4
            safi: unicast
        neighbor: 192.168.10.6
    vrf_name: VrfTenant1
sonic_config:
  lines: []
sonic_interfaces:
  - description: '"External"'
    enabled: true
    name: Eth1/5
  - description: '"Uplink to DC1-S1"'
    enabled: true
    name: Eth1/6
  - description: '"Uplink to DC1-S2"'
    enabled: true
    name: Eth1/7
  - description: '"MCLAG"'
    enabled: true
    name: Eth1/8
  - description: '"MCLAG"'
    enabled: true
    name: Eth1/9
  - description: router-id
    name: '{{ loopback_inf0 }}'
  - description: vtep
    name: '{{ loopback_inf1 }}'
  - description: Multisite
    name: '{{ loopback_inf3 }}'
sonic_l2_interfaces:
  - name: Eth1/5
    trunk:
      allowed_vlans:
        - vlan: 4000
  - name: PortChannel100
    trunk:
      allowed_vlans:
        - vlan: 100
        - vlan: 200
        - vlan: 201
        - vlan: 202
        - vlan: 301
        - vlan: 302
        - vlan: 303
        - vlan: 304
        - vlan: 305
        - vlan: 306
        - vlan: 307
        - vlan: 308
        - vlan: 309
        - vlan: 310
        - vlan: 61
        - vlan: 62
sonic_l3_interfaces:
  - ipv6:
      enabled: true
    name: Eth1/6
  - ipv6:
      enabled: true
    name: Eth1/7
  - ipv4:
      addresses:
        - address: '{{ loopback0_ip }}'
    name: '{{ loopback_inf0 }}'
  - ipv4:
      addresses:
        - address: '{{ loopback1_ip }}'
    name: '{{ loopback_inf1 }}'
  - ipv4:
      addresses:
        - address: '{{ loopback3_ip }}'
    name: '{{ loopback_inf3 }}'
  - ipv4:
      addresses:
        - address: 192.168.10.1/30
    name: Vlan4000
sonic_lag_interfaces:
  - members:
      interfaces:
        - member: Eth1/8
        - member: Eth1/9
    name: PortChannel100
sonic_system:
  anycast_address:
    ipv4: true
    mac_address: '{{ anycast_mac_address }}'
  hostname: DC1-R3L1
  interface_naming: standard
sonic_vlans:
  - vlan_id: 4000
  - vlan_id: 100
  - vlan_id: 200
  - vlan_id: 201
  - vlan_id: 202
  - vlan_id: 301
  - vlan_id: 302
  - vlan_id: 303
  - vlan_id: 304
  - vlan_id: 305
  - vlan_id: 306
  - vlan_id: 307
  - vlan_id: 308
  - vlan_id: 309
  - vlan_id: 310
  - vlan_id: 61
  - vlan_id: 62
sonic_vrf_interfaces:
  - members:
      interfaces:
        - name: Vlan100
        - name: Vlan61
        - name: Vlan200
        - name: Vlan201
        - name: Vlan202
        - name: Vlan301
        - name: Vlan302
        - name: Vlan303
        - name: Vlan304
        - name: Vlan305
        - name: Vlan4000
    name: VrfTenant1
  - members:
      interfaces:
        - name: Vlan62
        - name: Vlan306
        - name: Vlan307
        - name: Vlan308
        - name: Vlan309
        - name: Vlan310
    name: VrfTenant2
sonic_vxlans:
  - evpn_nvo: nvo1
    name: vtep5
    source_ip: '{{ loopback1_ip.split(''/'')[0] }}'
    vlan_map:
      - vlan: 100
        vni: 10100
      - vlan: 200
        vni: 10200
      - vlan: 201
        vni: 10201
      - vlan: 202
        vni: 10202
      - vlan: 301
        vni: 10301
      - vlan: 302
        vni: 10302
      - vlan: 303
        vni: 10303
      - vlan: 304
        vni: 10304
      - vlan: 305
        vni: 10305
      - vlan: 306
        vni: 10306
      - vlan: 307
        vni: 10307
      - vlan: 308
        vni: 10308
      - vlan: 309
        vni: 10309
      - vlan: 310
        vni: 10310
      - vlan: 61
        vni: 1061
      - vlan: 62
        vni: 1062
    vrf_map:
      - vni: 1061
        vrf: VrfTenant1
      - vni: 1062
        vrf: VrfTenant2
vlans:
  - 100
  - 200
  - 201
  - 202
  - 301
  - 302
  - 303
  - 304
  - 305
  - 306
  - 307
  - 308
  - 309
  - 310
vrfs:
  - VrfTenant1
  - VrfTenant2
